### ISSUE TITLE
Upload and download notifs.

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/comrades#14]
Upload and download will have notifs with a loader and then a uploaded/downloaded notif. 
Clicking on the downloaded(notif) one will open the file.
Make sure u don't create any memory leaks by passing contexts.

**Comment by Rushi98** [comment]
duplicate of #4

**Comment by aayushsingla** [comment]
How is this duplicate of #4 ? and sometimes passing context is important. If you want to show notification it is important to pass context.

**Comment by hardik124** [comment]
@tanmaydixit  . i highly doubt that passing context causes memory leaks. If in this case it is causing ( which can be shown by profiling ,i guess @aayushsingla  should make it a habit to put screenshot of profiler) , we can remedy that by making destroying context and running a garbage cleanup after that.

**Comment by aayushsingla** [comment]
This feature will be discussed in future. @hardik124  thanks for clearing the doubt regarding passing context.

**Comment by Rushi98** [comment]
Profiling is how I noticed the leak. Apart from that, I think we should keep various app components (like main ui, background services, long running tasks, notifs) independent from each other (i.e. one should not block other)
