### ISSUE TITLE
merge permission activities

### ISSUE THREAD

**Issue by Rushi98** [MobileApplicationsClub/comrades#20]
Currently, we require following permissions - 
1. basic login (uid, email, photoUrl etc)
2. drive permissions and token
3. local file permissions
4. sharing permissions for a particular file

- These can be put in single activity with no ui. 
- The exact permission to take can be taken via extras bundle.
- This will have benefit of easy access to primary permission. (For example, If file sharing permission is requested and it is detected that drive permission is not given, we can readily call the function for drive permission)
- Added benefit : All permission code at same place and so easy to manage.

**Comment by aayushsingla** [comment]
Right now 1, 2 and 3 are in one activity and 4 in one seperate activity. I think keeping them in exsisting way is a good idea because top 3 are basic permissions and 4 is needed only at particular occasions. Also, these activities are implemented already with the ways suggested.

**Comment by aayushsingla** [comment]
Also, 1,2,3 needed to be checked for both downloading and uploading.Howevet, 4 is specific to uploading only.

**Comment by Rushi98** [comment]
1. is done in two separate activities. (It is a duplication) Can be merged together

**Comment by aayushsingla** [comment]
So, i guess the issue should be to remove login from Course list?

**Comment by Rushi98** [comment]
Yes
