### ISSUE TITLE
a bottom nav in Home Activity

### ISSUE THREAD

**Issue by aayushsingla** [MobileApplicationsClub/comrades#21]
Home activity should have two tabs: one for all courses and one for pinned courses. User specific data for pinned courses need not be stored online and can be stored locally.

**Comment by Rushi98** [comment]
Instead of tabs, we can show pinned / followed courses first and then normal courses.

**Comment by aayushsingla** [comment]
It can be done that way also. But, i really feel it will be better to use two tabs for this.This will look more clean as we will have many courses and there is a great chance that all the courses will look like a sort of mess together.

**Comment by aayushsingla** [comment]
three tabs: My courses, All courses and User Profile should be added. The bottom nav can hide on scrolling up and become visible on user scrolling down(just an idea).This is an important issue because right now the navigation for user in the app is very limited. @tanmaydixit @Rushi98 please post your suggestions.

**Comment by Rushi98** [comment]
I think this is not necessary for initial release.

**Comment by aayushsingla** [comment]
solved #26
