### ISSUE TITLE
Fixing Add Course Issue and Changing Google uuid to firebase uuid

### ISSUE THREAD

**Issue by aayushsingla** [MobileApplicationsClub/comrades#28]
This issue should be fixed and key "addedById" stored in firebase should be changed to firebase uuid from google uuid when a course is added. Also, the app crashes with the following log:  @Rushi98
> java.lang.IllegalStateException: Gson().fromJson(sharedPr… ""), Person::class.java) must not be null at com.macbitsgoa.comrades.persistance.DataRepository.createCourse(DataRepository.kt:143) at com.macbitsgoa.comrades.courseListFragment.AddCourseVm.createCourse(AddCourseVm.kt:16)

**Comment by Rushi98** [comment]
How to reproduce the error?

**Comment by aayushsingla** [comment]
Fixed in #29
