### ISSUE TITLE
Add whatsapp type downloading and uploading

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/comrades#4]
refer db structure in #10 
We will set corresponding variables in db for the material in async task. In the vh, we will listen for these changes and update ui accordingly.

**Comment by aayushsingla** [comment]
@Rushi98 r u working on this?

**Comment by Rushi98** [comment]
We will first need to figure out what material data needs to be saved in db. I'm busy this week, we'll work on these two issues together. Till then, can you make a doc as to how exactly drive APIs work, we'll need both the request params and response format.
