### ISSUE TITLE
Fetching All Courses when spash screen is visible

### ISSUE THREAD

**Issue by aayushsingla** [MobileApplicationsClub/comrades#43]
If not done this may lead to crash in Imp. Docs and problems in search if user directly opened them without opening All courses fragment.
Steps to reproduce:
1.clear app data
2. open My docs or search some course

PS: This won't happen if  all courses fragment is opened before doing step 2.

**Comment by aayushsingla** [comment]
Working on this issue.

**Comment by aayushsingla** [comment]
1.Then it will show a message to check your internet connection
2.Courses will be fetched only on first run of the app.So, message for internet connection will be shown only for the first time.

**Comment by Rushi98** [comment]
@aayushsingla _why_ does this lead to crash ?

**Comment by aayushsingla** [comment]
because, Course Material is linked to the respective courses using foreign key. When you open Imp. Docs, you are trying to fetch material first before fetching the course itself.Hence, the app crashes.

**Comment by Rushi98** [comment]
Then we can hard code "imp docs" course on first launch.

**Comment by aayushsingla** [comment]
Actually, search is also a problem. If you try to search from home activity without opening All courses it wont show anything because no course is available in local database.

**Comment by Rushi98** [comment]
For search, we will download courses in background as app launches. Search will show more results as courses are fetched.
