### ISSUE TITLE
Add follow button [notifications]

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/comrades#5]
A follow toggle button will be infront of every subject(folder) this will be used to send notif of new files being added in that folder(subject).
Details.
The notif received by the user will be text, having details like [name] added [file name] to [subject]. Check it out! 
On clicking the notif that subject page will open up.
[more details coming soon, feel free to suggest in the comments]

**Comment by Rushi98** [comment]
instead of toggle button, can we keep this in a dialog menu which will show on long press

**Comment by Rushi98** [comment]
this also depends on #10

**Comment by aayushsingla** [comment]
Fixed in #29
