### ISSUE TITLE
File Picker fail with certain Images

### ISSUE THREAD

**Issue by aayushsingla** [MobileApplicationsClub/comrades#53]
Fatal Exception: 

```
java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=65537, result=-1, data=Intent { 
dat=content://com.google.android.apps.docs.storage/document/acc=2;doc=138 flg=0x1 
launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }} to activity 
{com.macbitsgoa.comrades/com.macbitsgoa.comrades.coursematerial.CourseActivity}: 
java.lang.NullPointerException
```

**Comment by aayushsingla** [comment]
This problem is due to the files which don't actually exist on the device like Google Drive Files.Thus, the app crashes whenever a user tries to upload such files.There are two ways of solving this problem:
1. Download the file when user clicks such a file and then use this file to upload on the app.But, this will be too much work on the main thread and we can't actually ask user to wait till the file gets downloaded.
2. Showing user the message that file doesn't exist on the device and he can't select such files.

I think option 2 should be our choice.

**Comment by shreyasnbhat** [comment]
If they already exist on Google Drive don't you have a choice to make them public via the API and download it to the device?

**Comment by shreyasnbhat** [comment]
As in if the file is on Drive already why download and upload it? Maybe change some file properties using the Drive API so that it becomes visible to others.
