### ISSUE TITLE
Minor UI changes

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/comrades#59]
- [x] The recents have a clash between text and timestamp.
- [x] The ranklist misses the no. of uploads. 
- [x] Loading dialog(the round one) while opening filelists for each courses.
- [x] 3 dot menu option needs to white in color.
- [x] The search menu needs to white in icons, hints and words.
- [x] Privacy will become Privacy Policy
- [x] Remove/Hide Bell icon/option from My Courses.

**Comment by aayushsingla** [comment]
@tanmaydixit 
can't understand 3 and 4
